/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 *
 *  AIM OF THIS PROJECT
 *  toggling the onboard Led with the help of the on board button when the button is pressed
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"
#include "stm32f407_driver.h"
void delay(void){
	for(uint32_t i=0; i< 500000/2;i++);
}
int main(void)
{
	GPIO_Handle_t GpioLed,GpioButton;
	// for the LED
	GpioLed.pGPIOx = GPIOD;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLed.GPIO_PinConfig.GPIO_OPType = GPIO_OP_TYPE_OD;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;

	GPIO_periClockControl(GPIOD,ENABLE); // enabling the clock control

	GPIO_Init(&GpioLed);

	// button on board
	GpioButton.pGPIOx = GPIOA;
	GpioButton.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GpioButton.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GpioButton.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioButton.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIO_periClockControl(GPIOA,ENABLE); // enabling the clock control
	GPIO_Init(&GpioButton);


	while(1){
		delay(); // help also in dealing with the debouncing of the button
		if(GPIO_ReadFromInputPin(GPIOA,GPIO_PIN_NO_0)){
			//printf(" loop executing \n");
			GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);
			delay(); // help also in dealing with the debouncing of the button
		}
	}

return 0;
}
