/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"


int main(void)
{
	RCC_AHB1_ENR_t volatile *const pClkCtrlReg = (RCC_AHB1_ENR_t*)0x40023830;
	GPIOx_MODE_t volatile *const pPortDModeReg = (GPIOx_MODE_t*)0x40020C00;
	GPIOx_ODR_t volatile *const pPortDOutReg = (GPIOx_ODR_t*)0x40020C14;


	pClkCtrlReg ->gpio_d_en =1;
	pPortDModeReg ->pin_12 =1;
	pPortDModeReg ->pin_13 =1;
	pPortDModeReg ->pin_14 =1;
	pPortDModeReg ->pin_15 =1;

	while(1){
		pPortDOutReg -> pin_12 =1;
		for(uint32_t i = 0;i<300000;i++);
		pPortDOutReg -> pin_13 =1;
		for(uint32_t i = 0;i<300000;i++);
		pPortDOutReg -> pin_14 =1;
		for(uint32_t i = 0;i<300000;i++);
		pPortDOutReg -> pin_15 =1;
		for(uint32_t i = 0;i<300000;i++);

		pPortDOutReg -> pin_12 =0;
		for(uint32_t i = 0;i<300000;i++);
		pPortDOutReg -> pin_13 =0;
		for(uint32_t i = 0;i<300000;i++);
		pPortDOutReg -> pin_14 =0;
		for(uint32_t i = 0;i<300000;i++);
		pPortDOutReg -> pin_15 =0;
		for(uint32_t i = 0;i<300000;i++);


		for(uint32_t i = 0; i<300000;i++);
	}
	return 0;
}
