/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407_driver.h"
void delay(){
	for(uint32_t i=0;i<500000;i++);
}

void GPIO_SUPPORT1(GPIO_RegDef_t *port,uint16_t pin, uint8_t ENORDI){
	GPIO_Handle_t GpioLed;
	GpioLed.pGPIOx = port;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = pin;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

	GPIO_periClockControl(port,ENORDI);
	GPIO_Init(&GpioLed);


}
int main(void)
{
	GPIO_Handle_t Button;
	Button.pGPIOx = GPIOA;   // NEED TO CHANGE
	Button.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	Button.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	Button.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	Button.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GPIO_periClockControl(GPIOA,ENABLE);
	GPIO_Init(&Button);

	GPIO_SUPPORT1(GPIOD,GPIO_PIN_NO_12,ENABLE);
	GPIO_SUPPORT1(GPIOD,GPIO_PIN_NO_13,ENABLE);
	GPIO_SUPPORT1(GPIOD,GPIO_PIN_NO_14,ENABLE);
	GPIO_SUPPORT1(GPIOD,GPIO_PIN_NO_15,ENABLE);
	uint8_t status = 1 ;
	while(status){
		if(GPIO_ReadFromInputPin(GPIOA,GPIO_PIN_NO_0)){
			delay();
			if (status == 1){
			// green led;
				GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);

			}
			else if (status ==2){
			// orange
				GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_13);
			}
			else if(status ==3){
			// red
				GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_14);
			}
			else{
			// blue
				GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_15);
			}
			if(status >= 5){
			     status = 0;
			}
			status += 1;
	}}

   return 0;
}
